monitoring_grafana_db_password: "Change-me-dont-Reuse-me"
monitoring_es_graylog_password: "Change-me-Too"
monitoring_graphite_api_influxdb_graphite_pass: "I-need-to-be-changed-too"
monitoring_grafana_domain: "grafana.example.com"
monitoring_graylog_domain: "graylog.example.com"
monitoring_grafana_admin_password: "I-need-to-be-stronger"
monitoring_grafana_github_client_secret: ""
monitoring_graphite_api_influxdb_admin_pass: "Intentionally-unencrypted"
monitoring_setup_type: "single-host"
monitoring_certbot_mail_address: "info@example.com"
monitoring_graylog_password_secret: "ArbitrarirylLongPasswordAtLeast20Characters"
monitoring_graylog_root_password: "Ansible-Vault-Secrets"
monitoring_sentry_db_password: "Please-Change-Me"
monitoring_sentry_domain: "sentry.example.com"
monitoring_use_certbot: false
monitoring_ssl_cert_directory: "{{ inventory_dir }}/files/ssl"
monitoring_ssl_cert: "certificate.pem"
monitoring_ssl_key: "key.pem"