---
rapidpro_postgresql_ssl_domain: "example.org"


rapidpro_backup_gpg_key_id: "B66789D5"
lb_backup_gpg_directory: "{{ inventory_dir }}/files/gpg"
rapidpro_backup_gpg_private_key: "{{ lb_backup_gpg_directory }}/{{ rapidpro_backup_gpg_key_id }}-priv.key"
rapidpro_backup_gpg_public_key: "{{ lb_backup_gpg_directory }}/{{ rapidpro_backup_gpg_key_id }}-pub.key"
rapidpro_backup_gpg_trust_file: "{{ lb_backup_gpg_directory }}/{{ rapidpro_backup_gpg_key_id }}-ultimate.trust"
rapidpro_backup_gpg_pass: "secret"
