---
- hosts: rapidpro_elasticsearch
  gather_facts: true
  become: true
  collections:
    - onaio.rapidpro
  pre_tasks:
    - name: load in Rapidpro vars
      include_vars:
        file: "../vars/{{ rapidpro_setup_type }}.yml"
    - include_tasks: tasks/python3-ubuntu.yml
    - name: Setup Ansible
      setup:
  roles:
    - role: elastic.elasticsearch

    - role: certbot
      when: es_use_certbot

    - role: nginx
      when: es_use_nginx is not defined or es_use_nginx