---
- hosts: rapidpro_redis
  gather_facts: true
  become: true
  pre_tasks:
    - name: load in Rapidpro vars
      include_vars:
        file: "../vars/{{ rapidpro_setup_type }}.yml"
    - include_tasks: tasks/python3-ubuntu.yml
    - name: Setup Ansible
      setup:
  roles:
    - redis